// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NT1B_wAuthentication.Data;

namespace NT1B_wAuthentication.Migrations
{
    [DbContext(typeof(MiContexto))]
    partial class MiContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NT1B_wAuthentication.Models.Direccion", b =>
                {
                    b.Property<int>("DireccionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calle");

                    b.Property<int>("Numero");

                    b.HasKey("DireccionId");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("NT1B_wAuthentication.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasMaxLength(50);

                    b.Property<bool>("Casado");

                    b.Property<int?>("DireccionId");

                    b.Property<int>("Edad");

                    b.Property<string>("Nombre");

                    b.HasKey("PersonaId");

                    b.HasIndex("DireccionId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("NT1B_wAuthentication.Models.Persona", b =>
                {
                    b.HasOne("NT1B_wAuthentication.Models.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId");
                });
#pragma warning restore 612, 618
        }
    }
}
